// <auto-generated />
using System;
using Gestion_de_salas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_de_salas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251116153908_una")]
    partial class una
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_de_salas.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Técnico en Veterinaria"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Técnico en Farmacia"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Técnico en Mantenimiento Industrial"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Técnico en Desarrollo de Video Juegos"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Técnico en Comunicación Digital"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Técnico en Ciberseguridad"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Técnico en Cosmetología y Estética Integral"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Técnico en Logística"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Técnico en Masoterapia"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Técnico en Odontología"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Técnico en Enfermería"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Técnico en Párvulos y Básica"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Contabilidad General"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Administración de Empresas"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Técnico en Turismo"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Técnico en Trabajo Social"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Analista Programador"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Técnico en Proceso y Control de Calidad Alimentaria"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Técnico Agrícola"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Técnico en Vinicultura"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Prevención de Riesgos"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Técnico en Automatización y Control Industrial"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Técnico en Redes Eléctricas"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Topografía"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Técnico en Obras Civiles"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Técnico en Mecánica"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Técnico en Mecánica Automotriz y Autotrónica"
                        });
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaReserva")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("EstadoSala")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 4,
                            EstadoSala = "Disponible",
                            Nombre = "Sala A"
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 4,
                            EstadoSala = "Disponible",
                            Nombre = "Sala B"
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 4,
                            EstadoSala = "Disponible",
                            Nombre = "Sala C"
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 4,
                            EstadoSala = "Disponible",
                            Nombre = "Sala D"
                        });
                });

            modelBuilder.Entity("Gestion_de_salas.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Docente"
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Estudiante"
                        });
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido1 = "Basoalto",
                            Apellido2 = "Gallegos",
                            Email = "gbasoalto24@cftsa.cl",
                            Estado = true,
                            Nombre = "Gonzalo",
                            Password = "12345678",
                            Rut = "15907638-5",
                            TipoUsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Apellido1 = "Castillo",
                            Apellido2 = "Vera",
                            Email = "jcastillo24@cftsa.cl",
                            Estado = true,
                            Nombre = "Jairo",
                            Password = "12345678",
                            Rut = "11111111-1",
                            TipoUsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Apellido1 = "Castro",
                            Apellido2 = "Castro",
                            Email = "Jcastro24@cftsa.cl",
                            Estado = true,
                            Nombre = "Joel",
                            Password = "12345678",
                            Rut = "22222222-2",
                            TipoUsuarioId = 3
                        });
                });

            modelBuilder.Entity("Gestion_de_salas.Models.UsuarioCarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioCarreras");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Movimiento", b =>
                {
                    b.HasOne("Gestion_de_salas.Models.Reserva", "Reserva")
                        .WithMany("Movimientos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Reserva", b =>
                {
                    b.HasOne("Gestion_de_salas.Models.Sala", "Sala")
                        .WithMany("Reservas")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_de_salas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Usuario", b =>
                {
                    b.HasOne("Gestion_de_salas.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.UsuarioCarrera", b =>
                {
                    b.HasOne("Gestion_de_salas.Models.Carrera", "Carrera")
                        .WithMany("UsuarioCarreras")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_de_salas.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCarreras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Carrera", b =>
                {
                    b.Navigation("UsuarioCarreras");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Reserva", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Sala", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Gestion_de_salas.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioCarreras");
                });
#pragma warning restore 612, 618
        }
    }
}
